{
 "title": "TKE  Dashboard - 1",
 "description": "Just a personal dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Network Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network Usage - (Container Transmitted)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "container_network_transmit_bytes_total"
    }
   ]
  },
  {
   "title": "HTTP Request Volume",
   "type": "graph",
   "description": "Volume of http request over 24 hours",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kubelet_http_requests_total" }
   ]
  },
  {
   "title": "Network Usage - ( Contianer Recieved)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "container_network_receive_packets_total"
    }
   ]
  },
  { "title": "Hardware Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Usage - (Load Average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "container_cpu_load_average_10s" }
   ]
  },
  {
   "title": "Container Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "container_threads" }
   ]
  },
  {
   "title": "Memory Usage - Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "container_memory_usage_bytes" }
   ]
  },
  {
   "title": "Disk IO (seconds total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "node_disk_io_time_seconds_total"
    }
   ]
  }
 ]
}